// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcyNrL_6sDErQXwG9-do3LANTMh6nQ0T4',
    appId: '1:685191561219:web:2c693251a74426c1e9ce36',
    messagingSenderId: '685191561219',
    projectId: 'codechat-45ec2',
    authDomain: 'codechat-45ec2.firebaseapp.com',
    databaseURL: 'https://codechat-45ec2-default-rtdb.firebaseio.com',
    storageBucket: 'codechat-45ec2.appspot.com',
    measurementId: 'G-V3SL5V40WY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCv2HwmS1TPAJUMBwhtkV9Xrc4LUgg6D8',
    appId: '1:685191561219:android:e74a67b4d2c23a13e9ce36',
    messagingSenderId: '685191561219',
    projectId: 'codechat-45ec2',
    databaseURL: 'https://codechat-45ec2-default-rtdb.firebaseio.com',
    storageBucket: 'codechat-45ec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYeL8UHWFyXp1E560F-980t7G7L5gAVaE',
    appId: '1:685191561219:ios:b2911fd35010d985e9ce36',
    messagingSenderId: '685191561219',
    projectId: 'codechat-45ec2',
    databaseURL: 'https://codechat-45ec2-default-rtdb.firebaseio.com',
    storageBucket: 'codechat-45ec2.appspot.com',
    iosBundleId: 'com.difmo.difwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYeL8UHWFyXp1E560F-980t7G7L5gAVaE',
    appId: '1:685191561219:ios:b2911fd35010d985e9ce36',
    messagingSenderId: '685191561219',
    projectId: 'codechat-45ec2',
    databaseURL: 'https://codechat-45ec2-default-rtdb.firebaseio.com',
    storageBucket: 'codechat-45ec2.appspot.com',
    iosBundleId: 'com.difmo.difwa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcyNrL_6sDErQXwG9-do3LANTMh6nQ0T4',
    appId: '1:685191561219:web:3787ed2ba2a11235e9ce36',
    messagingSenderId: '685191561219',
    projectId: 'codechat-45ec2',
    authDomain: 'codechat-45ec2.firebaseapp.com',
    databaseURL: 'https://codechat-45ec2-default-rtdb.firebaseio.com',
    storageBucket: 'codechat-45ec2.appspot.com',
    measurementId: 'G-MZKH5Q4FZ8',
  );
}
